# Generated by Django 2.2.6 on 2019-11-02 05:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('desc', models.CharField(max_length=4000)),
                ('type', models.CharField(choices=[('E', 'Endpoint'), ('Prod', 'Product'), ('AUTO', 'Auto-created from vulnerability read')], max_length=16)),
                ('version_num', models.CharField(max_length=150, null=True)),
                ('features', models.TextField(null=True)),
                ('host_address', models.CharField(max_length=450, null=True)),
                ('domain', models.CharField(max_length=450, null=True)),
                ('mac_address', models.CharField(max_length=450, null=True)),
                ('hist_data', models.TextField(null=True)),
                ('business_crit', models.CharField(choices=[('0', 'None'), ('VL', 'Very Low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], max_length=9, null=True)),
                ('asset_dept', models.CharField(max_length=30, null=True)),
                ('est_worth', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('platform', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=300)),
                ('numProducts', models.IntegerField()),
                ('securityPosture', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(default='example@email.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VMA.Company')),
                ('companyList', models.ManyToManyField(default=[models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VMA.Company')], related_name='usersAll', to='VMA.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('vulnID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('severity', models.IntegerField()),
                ('dateDiscovered', models.DateField()),
                ('dateModified', models.DateField(auto_now=True)),
                ('dateResolved', models.DateField(null=True)),
                ('actionPlan', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('U', 'Unhandled'), ('M', 'Mitigated'), ('N', 'Unassigned'), ('F', 'False positive')], max_length=16)),
                ('scanType', models.CharField(choices=[('Z', 'Zap'), ('Nes', 'Nessus'), ('Nex', 'Nexpose'), ('Nm', 'Nmap'), ('M', 'Manual Input')], max_length=10)),
                ('reference', models.TextField(blank=True)),
                ('cvssScore', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('assetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMA.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('service', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('assetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMA.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('user', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('asset', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('vulnerability', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('company', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('perms', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('report', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('service', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('fileUpload', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=[False, False, False, False, False], size=5)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMA.Company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
